### ISSUE TITLE
ContainerProperties class | Argument 2: Cannot Convert System.Generics.List<string> to string

### ISSUE THREAD

**Issue by napsterhopes** [AzureCosmosDB/HierarchicalPartitionKeysFeedbackGroup#11]
While trying to implement example [here](https://github.com/AzureCosmosDB/HierarchicalPartitionKeysFeedbackGroup#net-v3-sdk) in a .net core 6 console application , i am getting this error "Argument 2: Cannot Convert System.Generics.List<string> to string" as **ContainerProperties** class expects **string** as second argument, not **List<string>**.
Please refer code as below.

`private static readonly string DatabaseName = ConfigurationManager.AppSettings["DatabaseName"];
    private static readonly string DataCollectionName = ConfigurationManager.AppSettings["CollectionName"];
    private static readonly string _endpointUri = "";
    private static readonly string _primaryKey = "";

    static async Task CreateNewContainer()
    {
        using (CosmosClient client = new CosmosClient(_endpointUri, _primaryKey))
        {
            DatabaseResponse databaseResponse = await client.CreateDatabaseIfNotExistsAsync(DatabaseName);
            Database targetDatabase = databaseResponse.Database;

            // List of partition keys, in hierarchical order. You can have up to three levels of keys.
            List<string> subpartitionKeyPaths = new List<string> { "/TenantId", "/UserId", "/TransactionId" };
            //string subpartitionKeyPaths = "/TenantId/UserId/TransactionId";
            // Get reference to database that container will be created in
            Database database = client.GetDatabase(DatabaseName);
            // Create container - Subpartitioned by TenantId -> UserId -> SessionId
            ContainerProperties containerProperties = new ContainerProperties(id: "ContainerName", partitionKeyPath: subpartitionKeyPaths);
            var container = await database.CreateContainerAsync(containerProperties, throughput: 400);
            //return newcontainer.StatusCode == System.Net.HttpStatusCode.Created;
        }
    }`

**Comment by napsterhopes** [comment]
@deborahc  , @SrinikhilReddy

**Comment by SrinikhilReddy** [comment]
Hi @napsterhopes This is a probable error if you are not using the preview version of the SDK. Hierarchical partitioning is supported on the preview version today.

**Comment by napsterhopes** [comment]
Thank you @SrinikhilReddy @deborahc  , I have tried installing VS 2022 preview and also latest .net SDK 7 but i am still facing the same error.
I have also tried enabling preview features from Tools->Options-> Environment and tried adding `<EnablePreviewFeatures>true</EnablePreviewFeatures>` in `.csproj` file , but it didn't helped in resolving the issue.

Can you please commit somewhere and share the sample you have used in your demonstration [here](https://youtu.be/oToAY8NGWA0?t=1697)?

**Comment by napsterhopes** [comment]
It is resolved now ,thank you @SrinikhilReddy .
Can you please commit somewhere and share the sample you have used in your demonstration [here](https://youtu.be/oToAY8NGWA0?t=1697)?

When is stable version expected to be released?
