### ISSUE TITLE
Update the sample code for subpartitionKeyPaths?

### ISSUE THREAD

**Issue by YipingRuan** [AzureCosmosDB/HierarchicalPartitionKeysFeedbackGroup#5]
https://github.com/AzureCosmosDB/HierarchicalPartitionKeysFeedbackGroup#net-v3-sdk

Seems this no longer works:
```csharp
new ContainerProperties(id: "ContainerName", partitionKeyPaths: subpartitionKeyPaths)
```
It is internal now? (sdk 3.27):
```csharp
// Summary:
        //     Initializes a new instance of the Microsoft.Azure.Cosmos.ContainerProperties
        //     class for the Azure Cosmos DB service.
        //
        // Parameters:
        //   id:
        //     The Id of the resource in the Azure Cosmos service.
        //
        //   partitionKeyPaths:
        //     The path to the partition key. Example: /location
        internal ContainerProperties(string id, IReadOnlyList<string> partitionKeyPaths)
csharp

**Comment by SrinikhilReddy** [comment]
Please use the preview version of the SDK to use the above ContainerProperties constructor. You can find preview versions with the suffix `-preview`. 

Refer links and supported versions below.

https://github.com/AzureCosmosDB/HierarchicalPartitionKeysFeedbackGroup#getting-started

**Comment by YipingRuan** [comment]
> Please use the preview version of the SDK to use the above ContainerProperties constructor. You can find preview versions with the suffix `-preview`.
> 
> Refer links and supported versions below.
> 
> https://github.com/AzureCosmosDB/HierarchicalPartitionKeysFeedbackGroup#getting-started

Yes it was in `3.17.0-preview`,  but not in the latest `3.27.0-preview` or `4.0.0-preview`.

In short, is this feature not longer supported?
