### ISSUE TITLE
post preview alterations to cosmosdb account

### ISSUE THREAD

**Issue by vigouredelaruse** [AzureCosmosDB/HierarchicalPartitionKeysFeedbackGroup#6]
hullo; congrats on furthering multenancy concerns on 'the platform'

 just wondering if
- onboarding causes irreversable changes to the associated cosmosdb account and what those might be
- what are the implications for onboarding a free tier cosmosdb account, and is this even possible

**Comment by SrinikhilReddy** [comment]
Hello @vigouredelaruse 

The feature is enabled now by default across all existing and new accounts[Free Tier too]. 

No changes will apply at an account level for using Hierarchical partitioning. Thanks.
